import os

path = 'd:/DOCUMENTS/CNPM/test/hospital-management/src/main/resources/static/referrals.html'
with open(path, 'r', encoding='utf-8', errors='ignore') as f:
    content = f.read()

replacements = {
    'Khng': 'Không',
    'Chua c': 'Chưa có',
    'c': 'có',
    'Da hon t?t': 'Đã hoàn tất',
    'Dang khm': 'Đang khám',
    'Ch? g?i khm': 'Chờ gọi khám',
    'yu c?u': 'yêu cầu',
    'Ti?p nh?n': 'Tiếp nhận',
    'Xc nh?n': 'Xác nhận',
    'Phng khm': 'Phòng khám',
    'bc si': 'bác sĩ',
    'phi?u khm': 'phiếu khám',
    'Ch?n phi?u khm': 'Chọn phiếu khám',
    'Ch?n khoa nh?n': 'Chọn khoa nhận',
    'Ch?n bc si': 'Chọn bác sĩ',
    'Khng th? t?i yu c?u chuy?n khoa/h?i ch?n.': 'Không thể tải yêu cầu chuyển khoa/hội chẩn.',
    'Chua c yu c?u.': 'Chưa có yêu cầu.',
    'Ch? duy?t': 'Chờ duyệt',
    'Ch? x?p giu?ng': 'Chờ xếp giường',
    'Ch? ti?p nh?n': 'Chờ tiếp nhận',
    'Da ti?p nh?n': 'Đã tiếp nhận',
    'H?i ch?n': 'Hội chẩn',
    'Chuy?n khoa': 'Chuyển khoa',
    'Khng c yu c?u ch? duy?t.': 'Không có yêu cầu chờ duyệt.',
    'Duy?t': 'Duyệt',
    'Khng th? t?i danh sch duy?t:': 'Không thể tải danh sách duyệt:',
    'Da g?i yu c?u thnh cng!': 'Đã gửi yêu cầu thành công!',
    'L?i: ': 'Lỗi: ',
    'L?i h? th?ng': 'Lỗi hệ thống',
    'Xc nh?n duy?t yu c?u ny?': 'Xác nhận duyệt yêu cầu này?',
    'Da duy?t!': 'Đã duyệt!',
    'Ti?p nh?n h?i ch?n': 'Tiếp nhận hội chẩn',
    'Ma yu c?u': 'Mã yêu cầu',
    'Ma b?nh nhn': 'Mã bệnh nhân',
    'Ly do': 'Lý do',
    'Thao tc': 'Thao tác',
    'tu?i': 'tuổi',
    'Chuy?n khoa & H?i ch?n': 'Chuyển khoa & Hội chẩn',
    'U?ng sau an': 'Uống sau ăn',
    'Xc nh?n ti?p nh?n h?i ch?n?': 'Xác nhận tiếp nhận hội chẩn?',
    'don v?': 'đơn vị',
    'KhA''ng cA3 thA''ng bAo nAo.': 'Không có thông báo nào.',
    'L-i ti thA''ng bAo:': 'Lỗi tải thông báo:',
    'L-i khi lu phiu khAm:': 'Lỗi khi lưu phiếu khám:',
    'khAm': 'khám',
    'KhAm': 'Khám',
    'bnh nhAn': 'bệnh nhân',
    'Bnh nhAn': 'Bệnh nhân',
    'bAo': 'báo',
    '`<nh': 'định',
    '`A': 'đã',
    '?A': 'Đã',
    '?ang': 'Đang',
    'vAo': 'vào',
    'thAnh cA''ng': 'thành công',
    'hA3a `n': 'hóa đơn',
    'kt qu': 'kết quả',
    'ch%': 'chỉ',
    '`n thu`c': 'đơn thuốc',
    'thu`c': 'thuốc',
    'vin phA-': 'viện phí',
    'Cnh bAo:': 'Cảnh báo:',
    'S` lng': 'Số lượng',
    'vt quA': 'vượt quá',
    't"n kho': 'tồn kho',
    'hin cA3': 'hiện có',
    '`i?u ch%nh': 'điều chỉnh',
    'HoAn tt': 'Hoàn tất',
    'lt khAm': 'lượt khám',
    'Vui lAng': 'Vui lòng',
    'ch?n': 'chọn',
    'mTt': 'một',
    'hAng `i': 'hàng đợi',
    '?n thu`c': 'Đơn thuốc',
    'Ch% `<nh': 'Chỉ định',
    'lu': 'lưu',
    'phiu': 'phiếu',
    'mY': 'mở',
    'k3': 'kỳ',
    'L?c b?': 'Lọc bỏ',
    'nh_ng': 'những',
    'l<ch': 'lịch',
    'h y': 'hủy',
    'hoc': 'hoặc',
    'hin th<': 'hiển thị',
    '`t': 'đặt',
    'CH"C N,NG': 'CHỨC NĂNG',
    'THA"NG BA?O': 'THÔNG BÁO',
    'ti': 'tải',
    'thA''ng': 'thông',
    'bAo': 'báo',
    'li': 'lại',
    'danh sAch': 'danh sách',
    'kt n`i': 'kết nối',
    '`n': 'đến',
    'mAy ch': 'máy chủ',
    'KhA''ng th': 'Không thể',
    'to': 'tạo',
    'CSDL': 'CSDL',
    'L-i': 'Lỗi'
}

for old, new in replacements.items():
    content = content.replace(old, new)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print('Done.')
