package com.nhom12.hospital.security;

public enum AutomationPermission {
    APPOINTMENT_SLOT_CHECK,
    APPOINTMENT_CAPACITY_CHECK,
    DRUG_ALLERGY_CHECK,
    LAB_ABNORMALITY_DETECT,
    DRUG_STOCK_ALERT,
    DRUG_EXPIRY_ALERT,
    APPOINTMENT_REMINDER_SEND,
    LAB_RESULT_NOTIFICATION_SEND,
    DUTY_ROSTER_NOTIFICATION_SEND
}